### PR TITLE
Update registry.toml

### PR DESCRIPTION
**Pull request by arjenmarkus**
I have made a small repository with modules from my Flibs project on SourceForge, The common theme is the creation and manipulation of discrete points in N-dimensional space. That sounds rather grandiose ;), but in essence that is what they are all about.
I have not included the documentation yet, as that is not in Markdown format.

### CODE REVIEW

**Comment by LKedward** [comment]
Hi Arjen, is the repo currently private? I get a 404 not found when I visit that address.

**Comment by arjenmarkus** [comment]
Hi Laurence,

I just checked: it is private. Stupid mistake :(. How do I make it public?

Op ma 3 aug. 2020 om 19:25 schreef Laurence Kedward <
notifications@github.com>:

**Comment by LKedward** [comment]
Easy mistake :)
Look for the 'Settings' tab along the top when you're viewing the repo on Github, click that then scroll right to the bottom to 'Danger Zone' and click 'Change visibility'

**Comment by arjenmarkus** [comment]
Ah, thanks! Done - I completely overlooked that bit of the page ... "Danger
zone" does not quite encourage a visit.

Op ma 3 aug. 2020 om 19:35 schreef Laurence Kedward <
notifications@github.com>:

**Comment by milancurcic** [comment]
Hi Arjen, can you please move your entry up in the file so that it's in alphabetic order (by package name). Sorry, this requirement is only mentioned in the README but we'll soon have a check in CI so that it's reported when a PR is submitted.

**Comment by arjenmarkus** [comment]
Hi Milan,

that should no particular problem. Give me a few minutes :).

Op vr 7 aug. 2020 om 16:09 schreef Milan Curcic <notifications@github.com>:

**Comment by arjenmarkus** [comment]
Moved the entry for pointsets to the right alphabetical position.

**Comment by arjenmarkus** [comment]
Done - correctly, I hope.

Op vr 7 aug. 2020 om 16:26 schreef Arjen Markus <arjen.markus895@gmail.com>:

**Review by milancurcic — APPROVED** [review]

**Review by LKedward — APPROVED** [review]
Builds fine with `fpm` on my machine and tests run :+1: 

Only minor point @arjenmarkus: I noticed you've committed the `build` folder to your git repo, is this intentional? This doesn't affect my review to add to the registry.

**Comment by arjenmarkus** [comment]
Oh, that was NOT intentional. Odd, or is that because of Github being
helpful and me not paying enough attention ...

Op vr 7 aug. 2020 om 16:49 schreef Laurence Kedward <
notifications@github.com>:

**Review by certik — APPROVED** [review]

**Comment by certik** [comment]
This was approved by multiple people. Merging.

**Pull request merged**
