### PR TITLE
Pull request for urbanjost

### PR DESCRIPTION
**Pull request by urbanjost**

### CODE REVIEW

**Comment by LKedward** [comment]
Thanks @urbanjost.
The CI checks are failing due to `M_Pixel` not having a `License` field in its `fpm.toml` file.
Let me know when you've added it and I can rerun the CI checks.

Thanks for adding the descriptions, however it was decided (see <https://github.com/fortran-lang/fpm/issues/34#issuecomment-626703567>) not to include such meta-data directly in the registry but to instead fetch it from each `fpm.toml` file.

This data is fetched automatically and stored in [index.json](https://github.com/fortran-lang/fpm-registry/blob/master/index.json) which is used for [this online page](https://fortran-lang.org/packages/fpm); unfortunately the `description` field isn't documented so no package currently in the registry defines a `description` field. If you add a description field to your packages, then it will show up on the website.

**Review by LKedward — APPROVED** [review]

**Comment by urbanjost** [comment]
Mystery solved.  The file passed the tests described in the README.md file but failed when pushed and I could not find a message explaining why. I could see some of the code looked like it defined a description field but it was not working right after trying several syntax tries so commented them out. Makes sense to read them from the individual sites but the description field needs documented, as you mentioned. Hopefully try two will look better. The packages page is very nice. The Fortran Wiki page allows anyone to add package descriptions themselves. I haven't had time to look at the page long enough, but curious how it will be moderated.  Thanks!

**Comment by LKedward** [comment]
Thanks for the feeback @urbanjost; yes the README should be updated to recommend use of the full validation script (`build_index.py`) which actually fetches the individual `fpm.toml` files.
I will also open issues for the `description` field in `fpm.toml` which isn't standard currently.

**Comment by LKedward** [comment]
This is now merged and I'm happy to say your packages are displaying nicely on [the website](https://fortran-lang.org/packages/fpm) __with descriptions!__ Apologies for the small font size of the descriptions, I will increase this.

(With descriptions, your fpm packages are also more 'searchable' using the package search box.)

**Comment by urbanjost** [comment]
Thank you for helping straighten that out. Hate to ask for more as you have done so much already, but looking at the general page of packages (not the fpm page per-se) they are binned into "categories"., but the fpm(1) registry is not. When fpm(1) has a search capability would it be useful to have a "category" or "keyword" descriptor as well as "description"?  Not only might it be useful for future searches, but might be nice for automatically categorizing the fpm registry page. Not sure if categories should be ignored if they are not part of a predefined list or not.

**Comment by LKedward** [comment]
> When fpm(1) has a search capability would it be useful to have a "category" or "keyword" descriptor as well as "description"? Not only might it be useful for future searches, but might be nice for automatically categorizing the fpm registry page. Not sure if categories should be ignored if they are not part of a predefined list or not.

I completely agree with you and this is something that I've also been thinking about recently. We loosely look to Rust's package manager `cargo` as a good example for how to do things and they do have [categories](https://doc.rust-lang.org/cargo/reference/manifest.html#the-categories-field) and [keywords](https://doc.rust-lang.org/cargo/reference/manifest.html#the-keywords-field) fields where the former must match predefined 'category slugs' for the particular registry. 

I've opened an issue for this here: <https://github.com/fortran-lang/fpm/issues/165>

**Pull request merged**
