### PR TITLE
add packages by @everythingfunctional

### PR DESCRIPTION
**Pull request by milancurcic**
Submitting packages by @everythingfunctional: iso_varying_string, jsonff, quaff, sqliteff, strff, vegetables.

@everythingfunctional please review, add specific versions if any (I only included latest/master), add any package I missed, or remove any that you don't think should be there.

Others, please review. IMO they pass all criteria from [here](https://github.com/fortran-lang/fortran-lang.org/blob/master/PACKAGES.md).

### CODE REVIEW

**Review by certik — APPROVED** [review]
In addition to the criteria that Milan mentioned, I suggest we also add:

* the name of the package is either:
  * specific enough that there is low chance of clashing with another package in the future
  * or general (such as `json`, `toml`, `fft`, `splines`, `fem`), but the package is a clear leader in the area and most agree to use the name for it; in addition, there is understanding with the author that if the package becomes unmaintained in the future, and another package could fill the needs, we will reuse the name for the new package in the future (bumping the major semantic version, to ensure no breakage to existing users).

All the packages in this PR satisfy this new criterion also.

**Review by LKedward — APPROVED** [review]
LGTM!

**Review by everythingfunctional — APPROVED** [review]

**Comment by everythingfunctional** [comment]
Thanks! This is great for now.

**Comment by milancurcic** [comment]
With majority approval, I'll go ahead and merge.

**Pull request merged**
