### PR TITLE
added finterp

### PR DESCRIPTION
**Pull request by jacobwilliams**
Added [finterp](https://github.com/jacobwilliams/finterp) for Multidimensional Linear Interpolation.

### CODE REVIEW

**Comment by jacobwilliams** [comment]
uh oh! what did I do wrong?

**Comment by awvwgk** [comment]
The registry wants the *copyright* entry as well. I listed the required keywords in https://github.com/fortran-lang/fpm-registry/issues/24.

**Comment by jacobwilliams** [comment]
ah I see. will fix

**Comment by certik** [comment]
+1 from me to merge once tests pass. The package has 32 stars, it seems this is useful to people.

**Review by LKedward — APPROVED** [review]

**Review by awvwgk — APPROVED** [review]

**Pull request merged**
