### PR TITLE
add to registry from @urbanjost

### PR DESCRIPTION
**Pull request by urbanjost**

### CODE REVIEW

**Comment by LKedward** [comment]
Thanks @urbanjost.
Seems there's an oddity in the github actions log where the standard error stream is not aligned properly with stdout; the error raised for M_draw is interspersed at the top of the [log](https://github.com/fortran-lang/fpm-registry/runs/1010214512):

```
toml.decoder.TomlDecodeError: Key group not on a line by itself. (line 12 column 1 char 210)
```

**Review by LKedward — APPROVED** [review]
I've built each package on my machine with `fpm` and all looks good.

For `M_CLI2` I get runtime errors (`Array bound mismatch`) with `gfortran 7.5.0` but these go away with `gfortran 10.1.0`. Might be an allocation-on-assignment issue, but I wasn't aware of any bugs with this in `gfortran 7`.

Can `M_CLI2` be specified as the latest version of `M_CLI` or is it fundamentally different/incompatible?

**Comment by urbanjost** [comment]
Fundamentally different now. I have a collection of command line and command parsers and one of them does do both what M_CLI and M_CLI2 do  but I am intentionally trying to seperate them and make them stand-alone (the original assumes there are many other libraries available).  These are basically rewrites using modern Fortran of the same functionality. M_CLI uses NAMELIST to eliminate the need for converting the strings to types; M_CLI2 uses a generic routine that must be called for each keyword. M_CLI is particulary easy to use if your values are preallocated or fixed size (as required by NAMELIST) while M_CLI2 works best with allocatable variables. I was hoping to add a few more for people to experiment with in hopes that it would help get a standard interface to emerge. They have a lot in common having started from the same code but the idea of seperating them is to allow them to diverge and to simplify their usage. What they are modeled on has the advantage of having been on dozens of systems with different compilers and only requiring f90 plus a GETARGS(3f) function and a huge number of features like automatic generation of  a curses(3) interface with context-sensitive help text but it is not available for placing on github. That does mean these are not nearly as vetted (being essentially new). So unfortunately these have not been tested with anything other than gfortran 8.3 although a good deal of effort has been made to make them standard-conforming.

The NAMELIST interface is particularly useful when you have dozens or even hundreds of options as it requires very little code to add parameters but now that many more codes may require an arbitrary number of values having something work with allocatable arrays can be worth the extra effort; and since not all compilers provide a standard-conforming NAMELIST can be more portable.

**Comment by certik** [comment]
What does the error "toml.decoder.TomlDecodeError: Key group not on a line by itself. (line 12 column 1 char 210)" mean? That seems like a syntax error in the toml file? I don't see any syntax error there.

**Comment by certik** [comment]
Ah I see: it's not in `registry.toml`, but right here: https://github.com/urbanjost/M_draw/blob/909e7981d37084e28bcac8ece369c10af3aa6d31/fpm.toml#L12

I think the syntax error is that you have to put a new line right after `[[test]]`.

**Comment by certik** [comment]
This brings me to an interesting issue: since we always check the latest version, it means that once we have hundreds of packages, and somebody submits a new PR with a new package, the chance that some unrelated package will fail is quite high, all they have to do is to push into master something that is broken. However, I think a good practice is to run a CI before merging into master, and ensure that the `fpm.toml` is correct. So if some package breaks, we can perhaps help with that. So maybe it's fine.

**Comment by LKedward** [comment]
> Fundamentally different now. ... These are basically rewrites using modern Fortran of the same functionality.

Many thanks for the explanation, that makes sense. These all seem like very well-developed and useful packages!

> I think the syntax error is that you have to put a new line right after `[[test]]`.

Yes it's in the `fpm.toml` for M_draw - specifically, the `toml` spec requires every key-value pair to be on a separate line.
(This invalid syntax is allowed by the toml package used by haskell fpm which lead to https://github.com/urbanjost/M_CLI/issues/2)

> ... somebody submits a new PR with a new package, the chance that some unrelated package will fail is quite high, all they have to do is to push into master something that is broken.

The CI is already setup to handle this by behaving differently for PRs and merge commits:
 - For PRs: the check only fails if the __new__ packages encounter an error (all errors still logged).
 - For merge commits: the check fails if __any__ packages encounters an error

Hence PR checks will succeed for new packages, but the subsequent merge may fail with an email notification.
I plan on adding a `cron` job to the github actions workflow to check all packages periodically.

**Comment by certik** [comment]
I see. Great thinking. I think this works.

**Pull request merged**
